version: "3.8"
services:
  app:
    container_name: go-infrastructure-app
    build:
      context: .
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_network
  db:
    container_name: go-infrastructure-app-db
    image: postgres:14.1-alpine
    env_file:
      - .env
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network

networks:
  app_network: